#!/usr/bin/env bash

CERT=/etc/letsencrypt/live/mothra.us.to/cert.pem
KEY=/etc/letsencrypt/live/mothra.us.to/privkey.pem

#http-server --ssl -p 443 -c-1 --cert ./cert.pem --key ./privkey.pem
http-server --ssl -p 443 -c-1 --cert $CERT --key $KEY
